
title: Armadhani Hiro Juni Permana
# logo: /assets/img/headshot_circle.png
# description: 
# show_downloads: true
baseurl: "" # Leave this empty unless your site is in a subdirectory
url: "https://armadhanihiro.github.io" # Your GitHub Pages URL
author: "Armadhani Hiro"

# Build Settings
theme: "jekyll-theme-cayman" # Change to the theme you're using
# markdown: "kramdown"
